In [6]:
from keras.layers import Dense, Dropout, LSTM, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import pandas as pd
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

In [7]:
input_file = 'input.csv'

In [8]:
def load_data(test_split = 0.5):
    df = pd.read_csv(input_file)
    df['sequence'] = df['sequence'].apply(lambda x: [int(e) for e in x.split()])
    df = df.reindex(np.random.permutation(df.index))

    train_size = int(len(df) * (1 - test_split))

    X_train = df['sequence'].values[:train_size]
    y_train = np.array(df['target'].values[:train_size])
    X_test = np.array(df['sequence'].values[train_size:])
    y_test = np.array(df['target'].values[train_size:])
    return pad_sequences(X_train), y_train, pad_sequences(X_test), y_test

In [9]:
X_train, y_train, X_test, y_test = load_data()
y_train[0] = 2

In [10]:
def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(LSTM(30, input_shape = (1,3)))
    model.add(Dense(3))
    print ('Compiling...')
    model.compile(loss='categorical_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
    return model
X_train, y_train, X_test, y_test = load_data()
reshape_fun = lambda in_df: in_df.reshape((in_df.shape[0], 1, in_df.shape[1]))
y_train[0] = 2
X_train = reshape_fun(X_train)
X_test = reshape_fun(X_test)
print(y_train)
test_encoder = LabelEncoder()
test_encoder.fit(y_train)

[2 0 1 1]


LabelEncoder()

In [12]:
X_train.shape

(4, 1, 3)

In [148]:
unique_train = np.unique(y_train)
unique_train + np.array([1,2,3])

array([1, 3, 5])

In [149]:
unique_train = np.unique(y_train)
y_train = np_utils.to_categorical(test_encoder.transform(y_train))
y_test = np_utils.to_categorical(np.hstack((test_encoder.transform(y_test),unique_train)))[:-3]

In [150]:
y_test.shape

(5, 3)

In [13]:
X_train

array([[[3, 2, 1]],

       [[4, 3, 1]],

       [[2, 2, 3]],

       [[1, 2, 3]]], dtype=int32)

In [152]:
model = create_model(len(X_train[0]))

print ('Fitting model...')
hist = model.fit(X_train, y_train, batch_size=64, nb_epoch=10, validation_split = 0.1, verbose = 1)

score, acc = model.evaluate(X_test, y_test, batch_size=1)
print('Test score:', score)
print('Test accuracy:', acc)

Creating model...
Compiling...
Fitting model...


/home/zhaoxizhang/miniconda3/lib/python3.6/site-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 3 samples, validate on 1 samples
Epoch 1/10
3/3 [==============================] - 1s 414ms/step - loss: 0.9087 - acc: 0.6667 - val_loss: 1.1038 - val_acc: 0.0000e+00
Epoch 2/10
3/3 [==============================] - 0s 2ms/step - loss: 0.8571 - acc: 0.6667 - val_loss: 1.1632 - val_acc: 0.0000e+00
Epoch 3/10
3/3 [==============================] - 0s 6ms/step - loss: 0.7689 - acc: 0.6667 - val_loss: 1.2490 - val_acc: 0.0000e+00
Epoch 4/10
3/3 [==============================] - 0s 4ms/step - loss: 0.7125 - acc: 0.6667 - val_loss: 1.5357 - val_acc: 0.0000e+00
Epoch 5/10
3/3 [==============================] - 0s 3ms/step - loss: 0.6522 - acc: 0.6667 - val_loss: 1.8940 - val_acc: 0.0000e+00
Epoch 6/10
3/3 [==============================] - 0s 2ms/step - loss: 0.6086 - acc: 0.6667 - val_loss: 2.2539 - val_acc: 0.0000e+00
Epoch 7/10
3/3 [==============================] - 0s 4ms/step - loss: 0.5824 - acc: 0.6667 - val_loss: 4.0055 - val_acc: 0.0000e+00
Epoch 8/10
3/3 [================

In [153]:
a = np.array([1,2,3,4])
a.reshape((1,2,2))
list(set([1,2,3]))

[1, 2, 3]